name: Create Dev to Main Pull Request
on:
  push:
    branches:
      - dev
jobs:
  create-main-pr:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run the Action
        uses: devops-infra/action-pull-request@v0.4.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          source_branch: dev
          target_branch: main
          title: "${{ github.repository	}}: Dev -> Main"
          body: "**Automated pull request**"
          assignee: ${{ github.actor }}
          ignore_users: "dependabot"
